version: "3"

services:

  server:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./log:/log

  client:
    build: card-transfer/
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - server